### ISSUE TITLE
Crash when adding audio

### ISSUE THREAD

**Issue by lucwastiaux** [lucwastiaux/anki-language-tools#18]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.37 (6d596c8f) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-02-07 09:19:24
Add-ons possibly involved: ⁨anki-language-tools⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/taskman.py", line 87, in _on_closures_pending
  File "aqt/taskman.py", line 59, in <lambda>
  File "/home/luc/.local/share/Anki2/addons21/anki-language-tools/editor.py", line 165, in apply_audio
    editor.note.fields[field_index] = sound_tag
AttributeError: 'NoneType' object has no attribute 'fields'

**Comment by lucwastiaux** [comment]
should be fixed in next release
