### ISSUE TITLE
crash when adding translation

### ISSUE THREAD

**Issue by lucwastiaux** [lucwastiaux/anki-language-tools#36]
```
Caught exception:
Traceback (most recent call last):
  File "/Users/edsonmichalkiewicz/Library/Application Support/Anki2/addons21/771677663/gui.py", line 231, in <lambda>
    action.triggered.connect(lambda: dialogs.add_translation_dialog(languagetools, browser, browser.selectedNotes()))
  File "/Users/edsonmichalkiewicz/Library/Application Support/Anki2/addons21/771677663/dialogs.py", line 1348, in add_translation_dialog
    add_transformation_dialog(languagetools, browser, note_id_list, constants.TransformationType.Translation)
  File "/Users/edsonmichalkiewicz/Library/Application Support/Anki2/addons21/771677663/dialogs.py", line 1336, in add_transformation_dialog
    dialog.setupUi()
  File "/Users/edsonmichalkiewicz/Library/Application Support/Anki2/addons21/771677663/dialogs.py", line 294, in setupUi
    self.pickDefaultFromToFields()
  File "/Users/edsonmichalkiewicz/Library/Application Support/Anki2/addons21/771677663/dialogs.py", line 351, in pickDefaultFromToFields
    self.fromFieldIndexChanged(from_field_index, initialization=True)
  File "/Users/edsonmichalkiewicz/Library/Application Support/Anki2/addons21/771677663/dialogs.py", line 360, in fromFieldIndexChanged
    language_name = self.languagetools.get_language_name(language_code)
  File "/Users/edsonmichalkiewicz/Library/Application Support/Anki2/addons21/771677663/languagetools.py", line 123, in get_language_name
    return self.language_list[language]
AttributeError: 'LanguageTools' object has no attribute 'language_list'
```

**Comment by lucwastiaux** [comment]
this seems to be a case where language_list in languagetools.py couldn't be retrieved. error with SSL verification / VPN?
