### ISSUE TITLE
Adding a card

### ISSUE THREAD

**Issue by Casartellii** [lucwastiaux/anki-language-tools#53]
A fatal error occurred, and Anki must close. Please report this message on the forums.
Anki 2.1.46 (94913ec2) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2021-08-15 23:49:49

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 41, in cmd
  File "aqt\webview.py", line 139, in _onCmd
  File "aqt\webview.py", line 586, in _onBridgeCmd
  File "aqt\hooks_gen.py", line 3962, in __call__
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\editor.py", line 150, in onBridge
    editor_manager.process_field_update(editor, str)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\editor_processing.py", line 138, in process_field_update
    from_deck_note_type_field = from_deck_note_type_field = self.languagetools.deck_utils.editor_get_dntf(editor, field_index)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\deck_utils.py", line 106, in editor_get_dntf
    deck_note_type = self.build_deck_note_type_from_editor(editor)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\deck_utils.py", line 98, in build_deck_note_type_from_editor
    deck_note_type = self.build_deck_note_type_from_addcard(note, editor.parentWindow)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\deck_utils.py", line 88, in build_deck_note_type_from_addcard
    deck_id = add_cards.deckChooser.selectedId()
  File "aqt\deckchooser.py", line 109, in selectedId
  File "aqt\deckchooser.py", line 61, in selected_deck_id
  File "aqt\deckchooser.py", line 73, in _ensure_selected_deck_valid
  File "anki\decks.py", line 250, in get
  File "anki\decks.py", line 166, in get_legacy
  File "anki\_backend\generated.py", line 232, in get_deck_legacy
  File "anki\_backend\__init__.py", line 126, in _run_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }

Caught exception:
Traceback (most recent call last):
  File "aqt\taskman.py", line 101, in _on_closures_pending
  File "aqt\taskman.py", line 71, in <lambda>
  File "aqt\operations\__init__.py", line 214, in wrapped_done
  File "concurrent\futures\_base.py", line 432, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "aqt\operations\__init__.py", line 199, in wrapped_op
  File "aqt\editor.py", line 536, in <lambda>
  File "anki\notes.py", line 191, in fields_check
  File "anki\_backend\generated.py", line 355, in note_fields_check
  File "anki\_backend\__init__.py", line 126, in _run_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }

**Comment by lucwastiaux** [comment]
Thanks for the report, let me try to reproduce this

**Comment by lucwastiaux** [comment]
Does this happen to all your decks ? or only some of them ? Which deck are you trying to add the note into ?

**Comment by Casartellii** [comment]
I've routinely come across bugs, but, oddly enough, all of them have happened while I was studying a deck that had no notes made using the add-on or while I was editing cards in the "Browse", being that one the first "fatal error". In that case, I don't quite remember, but I think I was reviewing a normal deck with no cards made using the add-on. I'm afraid I can't provide much information since I didn't pay attention at the moment, only copied and pasted the bug here (shame on me). For now on, I will keep my eyes peeled.
