### ISSUE TITLE
Every time I run rules for a note

### ISSUE THREAD

**Issue by Casartellii** [lucwastiaux/anki-language-tools#66]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.47 (dc156f34) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2021-09-08 18:23:51

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\gui.py", line 266, in <lambda>
    action.triggered.connect(lambda: dialogs.run_rules_dialog(languagetools, browser, browser.selectedNotes()))
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\dialogs.py", line 880, in run_rules_dialog
    dialog.setupUi()
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\dialogs.py", line 570, in setupUi
    self.layout_rules(vlayout)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\dialogs.py", line 274, in layout_rules
    from_language_name = self.languagetools.get_language_name(self.languagetools.get_language(from_dntf))
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\languagetools.py", line 124, in get_language_name
    return self.language_list[language]
AttributeError: 'LanguageTools' object has no attribute 'language_list'

**Comment by lucwastiaux** [comment]
Please try upgrading to a later version of Language Tools, I believe that issue should be gone.

**Comment by Casartellii** [comment]
Thank you!
