### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Casartellii** [lucwastiaux/anki-language-tools#80]
`A fatal error occurred, and Anki must close. Please report this message on the forums.
Anki 2.1.47 (dc156f34) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2021-12-30 03:25:38

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 541, in handler
  File "aqt\editor.py", line 480, in oncallback
  File "aqt\hooks_gen.py", line 1910, in __call__
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\1781298089\src\__init__.py", line 266, in on_load_note
    editor.web.evalWithCallback(right_side_html(index is not None), cb)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\1781298089\src\web\html.py", line 153, in right_side_html
    html_params["calendar"]                 = get_calendar_html() if conf_or_def("showTimeline", True) else ""
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\1781298089\src\web\html.py", line 275, in get_calendar_html
    res                     = mw.col.db.all("select distinct notes.id from notes where id > %s and id < %s order by id asc" %(nid_minus_day_of_year, nid_now))
  File "anki\dbproxy.py", line 66, in all
  File "anki\dbproxy.py", line 60, in _query
  File "anki\_backend\__init__.py", line 78, in db_query
  File "anki\_backend\__init__.py", line 96, in _db_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 541, in handler
  File "aqt\editor.py", line 480, in oncallback
  File "aqt\hooks_gen.py", line 1910, in __call__
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\editor.py", line 63, in loadNote
    deck_note_type = languagetools.deck_utils.build_deck_note_type_from_editor(editor)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\deck_utils.py", line 102, in build_deck_note_type_from_editor
    deck_note_type = self.build_deck_note_type_from_note_card(note, editor.card)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\deck_utils.py", line 82, in build_deck_note_type_from_note_card
    deck_note_type = self.build_deck_note_type(deck_id, model_id)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\deck_utils.py", line 118, in build_deck_note_type
    deck = self.anki_utils.get_deck(deck_id)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\anki_utils.py", line 71, in get_deck
    return aqt.mw.col.decks.get(deck_id)
  File "anki\decks.py", line 250, in get
  File "anki\decks.py", line 166, in get_legacy
  File "anki\_backend\generated.py", line 232, in get_deck_legacy
  File "anki\_backend\__init__.py", line 126, in _run_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }

Caught exception:
Traceback (most recent call last):
  File "aqt\taskman.py", line 101, in _on_closures_pending
  File "aqt\taskman.py", line 71, in <lambda>
  File "aqt\operations\__init__.py", line 214, in wrapped_done
  File "concurrent\futures\_base.py", line 432, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "aqt\operations\__init__.py", line 199, in wrapped_op
  File "aqt\editor.py", line 537, in <lambda>
  File "anki\notes.py", line 191, in fields_check
  File "anki\_backend\generated.py", line 355, in note_fields_check
  File "anki\_backend\__init__.py", line 126, in _run_command
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
`

**Comment by lucwastiaux** [comment]
Thanks for reporting this, it's a mysterious crash that I haven't yet been able to solve, but i'm going to keep looking
