### ISSUE TITLE
"Speak" button in the browser editor

### ISSUE THREAD

**Issue by Casartellii** [lucwastiaux/anki-language-tools#81]
Happened when clicked the "Speak" button in the browser editor.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.47 (dc156f34) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-01-06 23:47:27

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 41, in cmd
  File "aqt\webview.py", line 142, in _onCmd
  File "aqt\webview.py", line 589, in _onBridgeCmd
  File "aqt\hooks_gen.py", line 4000, in __call__
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\editor.py", line 135, in onBridge
    raise errors.AnkiNoteEditorError(f'No voice set for language {languagetools.get_language_name(field_language)}')
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\languagetools.py", line 136, in get_language_name
    return self.language_list[language]
AttributeError: 'LanguageTools' object has no attribute 'language_list'

**Comment by lucwastiaux** [comment]
I believe this is related to the other issue you've mentioned, there's something kind unreliable connection between your computer and the language tools server. I am not completely clear how to resolve this, but I'm studying various solutions.
