### ISSUE TITLE
Bug while verifying the API key.

### ISSUE THREAD

**Issue by Casartellii** [lucwastiaux/anki-language-tools#82]
Happened while I was verifying the my API key.

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.47 (dc156f34) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-01-06 23:47:27

Caught exception:
Traceback (most recent call last):
  File "urllib3\connection.py", line 169, in _new_conn
  File "urllib3\util\connection.py", line 96, in create_connection
  File "urllib3\util\connection.py", line 86, in create_connection
TimeoutError: [WinError 10060] Uma tentativa de conexão falhou porque o componente conectado não respondeu

corretamente após um período de tempo ou a conexão estabelecida falhou

porque o host conectado não respondeu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 353, in connect
  File "urllib3\connection.py", line 181, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001F88CE58190>: Failed to establish a new connection: [WinError 10060] Uma tentativa de conexão falhou porque o componente conectado não respondeu

corretamente após um período de tempo ou a conexão estabelecida falhou

porque o host conectado não respondeu

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cloud-language-tools-nlp-prod.anki.study', port=443): Max retries exceeded with url: /verify_api_key (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F88CE58190>: Failed to establish a new connection: [WinError 10060] Uma tentativa de conexão falhou porque o componente conectado não respondeu\r\ncorretamente após um período de tempo ou a conexão estabelecida falhou\r\nporque o host conectado não respondeu'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt\taskman.py", line 101, in _on_closures_pending
  File "aqt\taskman.py", line 71, in <lambda>
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\dialog_apikey.py", line 103, in verify_api_key_done
    is_valid, message = future_result.result()
  File "concurrent\futures\_base.py", line 432, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\dialog_apikey.py", line 100, in verify_api_key_background
    return self.languagetools.verify_api_key(api_key_text)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\languagetools.py", line 106, in verify_api_key
    result = self.cloud_language_tools.api_key_validate_query(api_key)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\771677663\cloudlanguagetools.py", line 21, in api_key_validate_query
    response = requests.post(self.base_url + '/verify_api_key', json={
  File "requests\api.py", line 119, in post
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cloud-language-tools-nlp-prod.anki.study', port=443): Max retries exceeded with url: /verify_api_key (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F88CE58190>: Failed to establish a new connection: [WinError 10060] Uma tentativa de conexão falhou porque o componente conectado não respondeu\r\ncorretamente após um período de tempo ou a conexão estabelecida falhou\r\nporque o host conectado não respondeu'))

**Comment by lucwastiaux** [comment]
Thanks, it's something I've been tracking for a while. Do you use a VPN ? and which country are you connecting from ?

**Comment by Casartellii** [comment]
Yes, I use VPN. I'm from Brazil but normally I'm using a USA IP provided by the VPN.

**Comment by lucwastiaux** [comment]
Do you still get this without the VPN ? How reliable is your VPN ?

**Comment by Casartellii** [comment]
Unfortunately, I can't reproduce the issue anymore. I've been using [Proton VPN](https://protonvpn.com/l), I think is quite reliable.
